### ISSUE TITLE
Class File_Reflector should be compatible...

### ISSUE THREAD

**Issue by 23r9i0** [WordPress/phpdoc-parser#177]
...
Warning: Declaration of WP_Parser\File_Reflector::isNodeDocumentable(PHPParser_Node $node) should be compatible with phpDocumentor\Reflection\FileReflector::isNodeDocumentable(PhpParser\Node $node) in phpdoc-parser/lib/class-file-reflector.php on line 14
Fatal error: Declaration of WP_Parser\File_Reflector::enterNode(PHPParser_Node $node) must be compatible with PhpParser\NodeVisitor::enterNode(PhpParser\Node $node) in phpdoc-parser/lib/class-file-reflector.php on line 14

**Comment by JDGrimes** [comment]
Sounds like you have the wrong version of phpDocumentor/PhpParser.

**Comment by 23r9i0** [comment]
yes, but composer install 1.4.1 version of nikic/php-parser and change names for namespace, classes, ... see https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-1.0.md

**Comment by JDGrimes** [comment]
Apparently phpDocumentor/Reflection doesn't follow semantic versioning, since it updated it sdependency [from PHP-Parser 0.9 to 1.0](https://github.com/phpDocumentor/Reflection/commit/8cbe6615ee5809c8d2bfad25d0206f980cd6a595#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L15)  in [version 1.1.0](https://github.com/phpDocumentor/Reflection/releases/tag/1.1.0). Actually, I think this was an unintentional break on their part. I'll see if maybe they can fix this somehow. In the mean time, try installing version 1.0.7 of phpDocumentor/Reflection instead, which will have the correct dependency versions that are compatible with this plugin.

**Comment by JDGrimes** [comment]
I've opened https://github.com/phpDocumentor/Reflection/issues/96.

**Comment by JDGrimes** [comment]
@23r9i0 phpDocumentor has resolved this issue by removing the 1.1.0 release. I think you will be able to re-install using composer now and it should install the correct version of PHP-Parser.

**Comment by 23r9i0** [comment]
ok, thanks!!
