### ISSUE TITLE
Code not updated on repeated wp parser create

### ISSUE THREAD

**Issue by FlorianBrinkmann** [WordPress/phpdoc-parser#194]
At first: I try to use the parser to create a code reference for my WordPress themes, so I do not use the theme from the W.org code reference.

Everything works fine on the first create statement. I use a few functions from the code reference theme, like get_source_code(). Now the problem: If I modify the code of a theme and run another `wp parser create`, the meta field with the code does not get an update. I searched in the wporg-developer theme if this uses a custom function to update that field, but does not find something…

I tried to hook into the `save_post` action and run a `get_source_code( null, true )`, but it seems that the action is not fired by the WP-CLI command.

Is there a default way to do this?

Otherwise, I would try to loop through all the parser posts in a function hooked to `wp_parser_ending_import` and run a `get_source_code()` with force parse, but that seems not so ideal to me.

Thanks in advance!

**Comment by DrewAPicture** [comment]
@coffee2code Any insight here?

**Comment by coffee2code** [comment]
Hi @FlorianBrinkmann,

Parsing and caching source code in post meta is a feature of the wporg-developer theme for the code reference and not the wp-parser itself.

By default, the theme parses the source code for a function/method/class (via `get_source_code()`) if it hadn't been parsed before (i.e. if there isn't a value in the `_wp-parser_source_code` meta field). This you no doubt already know.

As you've deduced, after the code has been parsed once it does not attempt to update it again. That's because the way we run things on the code reference is that we always pre-cache the source for all the elements that show source code after each parsing (similar to what you suggest at the end of your ticket).

I use a function like so, which I manually invoke via wp-cli:

```
/**
 * Primes the source code post meta for post types meant to display their source.
 */
function devhub_prime_post_meta_source_code() {
	$post_types_with_source_code = array(
		'wp-parser-class',
		'wp-parser-method',
		'wp-parser-function',
	);
	foreach( $post_types_with_source_code as $post_type ) {
		$posts = get_posts( array(
			'fields' => 'ids',
			'post_type' => $post_type,
			'posts_per_page' => '-1',
		) );
		foreach ( $posts as $post ) {
			echo "Getting source for: {$post}\n";
			get_source_code( $post, true );
		}
	}
	die( "DONE\n" );
}

```
In cases where the real-time parsing of source code is fine (which is the default), after a parsing you could delete all existing `_wp-parser_source_code` meta fields. That would remove the cached parsed source code, forcing them to get reparsed the next time they are needed.

We would certainly welcome alternative approaches, or at least adding the above to the theme itself. Requests in this regard should be made for the theme at https://meta.trac.wordpress.org/ (be sure to set "Developer Hub" as the component).

Cheers!

**Comment by FlorianBrinkmann** [comment]
Great, thanks for the insights :) I took a deeper look into the plugin files today and found the `wp_parser_import` action, which seems to fit my needs very well. With that, I just need this piece of code:

```php
/**
 * Updates code meta field after item was imported.
 *
 * @param int $post_id Optional; post ID of the inserted or updated item.
 */
function fbn_update_code_meta_field_after_item_import( $post_id ) {
	/**
	 * Check if we have $post_id.
	 */
	if ( $post_id ) {
		/**
		 * Force regeneration of the code meta field.
		 */
		fbn_get_source_code( $post_id, true );
	}
}

add_action( 'wp_parser_import_item', 'fbn_update_code_meta_field_after_item_import' );
```

I will take a look at the meta trac and see if I can file a ticket with a patch :)
