### ISSUE TITLE
Question: Avoiding /wp-content/ directory?

### ISSUE THREAD

**Issue by maheshwaghmare** [WordPress/phpdoc-parser#195]
I think we need to avoid `/wp-content/` directory while building Code Reference. Current doc generates the code reference of default themes (`Twenty Ten`, `Twenty Twelve` etc) @see [twentyten_setup()](https://developer.wordpress.org/reference/functions/twentyten_setup/) & plugin (`Hello Dolly`) @see
[hello_dolly()](https://developer.wordpress.org/reference/functions/hello_dolly/)

```
// Avoid 'wp-content' Directory
if( strpos($file->getFilename(), 'wp-content') === false ) {
...
}
```

**Comment by maheshwaghmare** [comment]
I think we keep these intentionally because `Code Reference` is the Complete reference for WordPress **(It includes the default plugins & themes)**.

**Comment by keesiemeijer** [comment]
The default themes were parsed to Twenty Fourteen. Third party libraries are also excluded when parsing (for the reference). Here you can see how I exclude the same directories and files to create a mirror of the reference.

https://github.com/keesiemeijer/wp-reference/blob/master/exclude-wp-external-libs.php

I think `Hello Dolly` and the default themes shouldn't be part of the reference though. Maybe that's why they stopped parsing the default themes.
